import type { Destination } from '../types/destination';

export const FEATURED_DESTINATIONS: Omit<Destination, 'id' | 'createdAt'>[] = [
  {
    name: 'Tokyo Pulse',
    country: 'Japan',
    teaser: 'Neon-lit nights, ancient temples, and street food that changes your life.',
    flightCost: 1200,
    hotelCost: 800,
    activityCost: 400,
    transferCost: 150,
    partnerFee: 50,
    isFeatured: true,
    previewImageUrl: null,
  },
  {
    name: 'Paris Afterglow',
    country: 'France',
    teaser: 'Golden hour over the Seine, hidden wine bars, and rooftop views.',
    flightCost: 900,
    hotelCost: 1000,
    activityCost: 350,
    transferCost: 100,
    partnerFee: 50,
    isFeatured: true,
    previewImageUrl: null,
  },
  {
    name: 'Bali Drift',
    country: 'Indonesia',
    teaser: 'Rice terraces at dawn, jungle villas, and surf breaks at sunset.',
    flightCost: 1100,
    hotelCost: 600,
    activityCost: 300,
    transferCost: 80,
    partnerFee: 50,
    isFeatured: true,
    previewImageUrl: null,
  },
];
