import type { ActiveTripGuide } from '@elsewhere/shared';

const DAY_MS = 24 * 60 * 60 * 1000;

function iso(daysFromNow: number, hour = 12): string {
  const date = new Date(Date.now() + daysFromNow * DAY_MS);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

export function listMockTripGuides(): ActiveTripGuide[] {
  const monitoredAt = new Date().toISOString();

  return [
    {
      tripId: 'mock-trip-tokyo',
      tripName: 'Tokyo 2026',
      tripTagline: 'Neon, quiet mornings, and a smoother way across the city.',
      destinationName: 'Tokyo',
      destinationCountry: 'Japan',
      status: 'booked',
      travelerCount: 2,
      totalCost: 4820,
      protectedValue: 1730,
      potentialSavings: 342,
      monitoredAt,
      segments: [
        {
          id: 'seg-tokyo-flight-out',
          kind: 'flight',
          providerName: 'United Airlines',
          title: 'UA 875 · SFO to HND',
          startsAt: iso(21, 10),
          endsAt: iso(22, 14),
          confirmationCode: 'UA8K2Q',
          routeSummary: 'San Francisco to Tokyo Haneda, nonstop',
          fareClass: 'Economy K',
          policySummary: 'No change fee on this fare family. Traveler pays fare difference; unused value becomes United travel credit if canceled before departure.',
        },
        {
          id: 'seg-tokyo-hotel',
          kind: 'hotel',
          providerName: 'Shinjuku Granbell Hotel',
          title: '5 nights in Shinjuku',
          startsAt: iso(22, 16),
          endsAt: iso(27, 11),
          confirmationCode: 'HJP-4192',
          routeSummary: null,
          fareClass: null,
          policySummary: 'Fully refundable until 48 hours before local check-in. After that, first night is nonrefundable.',
        },
      ],
      opportunities: [
        {
          id: 'opp-tokyo-earlier-flight',
          tripId: 'mock-trip-tokyo',
          kind: 'better_flight',
          status: 'action_available',
          title: 'Earlier nonstop saves $186',
          detail: 'United opened lower inventory on an earlier SFO to HND nonstop. Assist can move both travelers and keep the same arrival day.',
          actionLabel: 'Switch flights',
          priority: 1,
          savingsAmount: 186,
          protectedValue: null,
          deadlineAt: iso(20, 22),
          autoActionable: true,
          citations: [
            {
              label: 'United fare rule',
              detail: 'Economy K allows voluntary changes before departure with no change fee; fare difference is collected or returned as credit.',
            },
            {
              label: 'Trip constraint',
              detail: 'Hotel check-in remains valid because the alternate flight arrives before the original arrival time.',
            },
          ],
        },
        {
          id: 'opp-tokyo-hotel-window',
          tripId: 'mock-trip-tokyo',
          kind: 'cancellation_window',
          status: 'watching_deadline',
          title: 'Hotel free-cancel window closes soon',
          detail: 'You have a refundable hotel window now. After the deadline, canceling costs the first night.',
          actionLabel: 'Keep monitoring',
          priority: 2,
          savingsAmount: null,
          protectedValue: 612,
          deadlineAt: iso(19, 16),
          autoActionable: false,
          citations: [
            {
              label: 'Hotel policy',
              detail: 'Free cancellation until 48 hours before local check-in; first night penalty applies after cutoff.',
            },
          ],
        },
      ],
      cancellation: {
        tripId: 'mock-trip-tokyo',
        summary: 'Canceling today keeps most value as airline credit and preserves the hotel refund window.',
        refundAmount: 1290,
        travelCreditAmount: 1730,
        feeAmount: 0,
        decisionWindowEndsAt: iso(19, 16),
        creditExpiresAt: iso(386, 0),
        risks: [
          'Airfare returns as travel credit, not cash.',
          'Hotel refund drops by one night after the free-cancel window.',
          'Experience tickets become nonrefundable 7 days before arrival.',
        ],
      },
    },
    {
      tripId: 'mock-trip-paris',
      tripName: 'Paris 2026',
      tripTagline: 'Four nights, better timing, and more room for wonder.',
      destinationName: 'Paris',
      destinationCountry: 'France',
      status: 'booked',
      travelerCount: 4,
      totalCost: 7680,
      protectedValue: 2800,
      potentialSavings: 640,
      monitoredAt,
      segments: [
        {
          id: 'seg-paris-flight-out',
          kind: 'flight',
          providerName: 'Delta Air Lines',
          title: 'DL 8606 · JFK to CDG',
          startsAt: iso(34, 19),
          endsAt: iso(35, 8),
          confirmationCode: 'DL7P9M',
          routeSummary: 'New York JFK to Paris Charles de Gaulle, nonstop',
          fareClass: 'Main Cabin',
          policySummary: 'No change fee for Main Cabin international itinerary. Fare difference applies; basic economy restrictions do not apply.',
        },
        {
          id: 'seg-paris-hotel',
          kind: 'hotel',
          providerName: 'Hotel Rochechouart',
          title: '4 nights near Montmartre',
          startsAt: iso(35, 15),
          endsAt: iso(39, 11),
          confirmationCode: 'HR-8831',
          routeSummary: null,
          fareClass: null,
          policySummary: 'Rate can be rebooked if the public refundable rate drops before the free cancellation deadline.',
        },
      ],
      opportunities: [
        {
          id: 'opp-paris-hotel-rate',
          tripId: 'mock-trip-paris',
          kind: 'hotel_rate_drop',
          status: 'action_available',
          title: 'Same hotel is $454 cheaper',
          detail: 'The refundable public rate dropped for your dates. Assist can cancel and rebook the same room category before the penalty window.',
          actionLabel: 'Rebook hotel',
          priority: 1,
          savingsAmount: 454,
          protectedValue: null,
          deadlineAt: iso(32, 15),
          autoActionable: true,
          citations: [
            {
              label: 'Hotel cancellation rule',
              detail: 'Current booking is refundable until 72 hours before local check-in.',
            },
            {
              label: 'Rate comparison',
              detail: 'Same room category, same occupancy, same cancellation terms, lower public rate.',
            },
          ],
        },
        {
          id: 'opp-paris-group-credit',
          tripId: 'mock-trip-paris',
          kind: 'credit_protection',
          status: 'monitoring',
          title: 'Group credits remain separable',
          detail: 'If one traveler drops, the airline can retain that traveler’s value as an individual credit without canceling the group itinerary.',
          actionLabel: 'Explain options',
          priority: 3,
          savingsAmount: null,
          protectedValue: 700,
          deadlineAt: iso(33, 19),
          autoActionable: false,
          citations: [
            {
              label: 'Delta ticketing rule',
              detail: 'Each passenger coupon retains separate residual value when voluntarily canceled before scheduled departure.',
            },
          ],
        },
      ],
      cancellation: {
        tripId: 'mock-trip-paris',
        summary: 'Canceling today preserves airfare as individual credits and returns the hotel deposit.',
        refundAmount: 2120,
        travelCreditAmount: 2800,
        feeAmount: 0,
        decisionWindowEndsAt: iso(32, 15),
        creditExpiresAt: iso(399, 0),
        risks: [
          'Airline credit is traveler-specific.',
          'Some food tour deposits become nonrefundable 14 days before start.',
          'Rebooking later may increase fare difference.',
        ],
      },
    },
    {
      tripId: 'mock-trip-bali',
      tripName: 'Bali 2026',
      tripTagline: 'Rainforest mornings, surf at sunset, and time to breathe.',
      destinationName: 'Bali',
      destinationCountry: 'Indonesia',
      status: 'in_progress',
      travelerCount: 2,
      totalCost: 5210,
      protectedValue: 1180,
      potentialSavings: 0,
      monitoredAt,
      segments: [
        {
          id: 'seg-bali-return',
          kind: 'flight',
          providerName: 'Singapore Airlines',
          title: 'SQ 947 + SQ 32 · DPS to SFO',
          startsAt: iso(2, 20),
          endsAt: iso(3, 18),
          confirmationCode: 'SQ2L6R',
          routeSummary: 'Denpasar to San Francisco via Singapore',
          fareClass: 'Economy Flexi',
          policySummary: 'Changes permitted before departure. Missed connection protection applies when all segments remain on the same ticket.',
        },
        {
          id: 'seg-bali-hotel',
          kind: 'hotel',
          providerName: 'Ubud Jungle Villas',
          title: 'Final night in Ubud',
          startsAt: iso(1, 15),
          endsAt: iso(2, 11),
          confirmationCode: 'UBD-1180',
          routeSummary: null,
          fareClass: null,
          policySummary: 'Stay is inside penalty window; unused final night is nonrefundable unless hotel grants weather waiver.',
        },
      ],
      opportunities: [
        {
          id: 'opp-bali-connection-risk',
          tripId: 'mock-trip-bali',
          kind: 'connection_risk',
          status: 'action_available',
          title: 'Connection risk detected',
          detail: 'Inbound weather at SIN makes your 55-minute connection fragile. Assist found a protected earlier DPS departure on the same ticket family.',
          actionLabel: 'Move return earlier',
          priority: 1,
          savingsAmount: null,
          protectedValue: 1180,
          deadlineAt: iso(2, 8),
          autoActionable: true,
          citations: [
            {
              label: 'Same-ticket protection',
              detail: 'Airline reaccommodation applies if the protected connection misconnects, but earlier voluntary move reduces overnight risk.',
            },
            {
              label: 'Fare rule',
              detail: 'Economy Flexi permits pre-departure changes; fare difference is currently zero on the earlier departure.',
            },
          ],
        },
      ],
      cancellation: {
        tripId: 'mock-trip-bali',
        summary: 'Canceling the return now is allowed but not recommended because the same-ticket protection is more valuable than the residual credit.',
        refundAmount: 0,
        travelCreditAmount: 1180,
        feeAmount: 0,
        decisionWindowEndsAt: iso(2, 20),
        creditExpiresAt: iso(368, 0),
        risks: [
          'Canceling breaks airline-protected connection handling.',
          'Hotel is already inside the penalty window.',
        'Replacement one-way fares are currently higher than retained credit.',
        ],
      },
    },
    {
      tripId: 'mock-trip-santorini',
      tripName: 'Santorini 2026',
      tripTagline: 'Aegean light, protected plans, and nothing rushed.',
      destinationName: 'Santorini',
      destinationCountry: 'Greece',
      status: 'booked',
      travelerCount: 2,
      totalCost: 4640,
      protectedValue: 1380,
      potentialSavings: 214,
      monitoredAt,
      segments: [
        {
          id: 'seg-santorini-flight',
          kind: 'flight',
          providerName: 'Aegean Airlines',
          title: 'A3 349 · ATH to JTR',
          startsAt: iso(48, 13),
          endsAt: iso(48, 14),
          confirmationCode: 'A3S8N2',
          routeSummary: 'Athens to Santorini, same-ticket connection from JFK',
          fareClass: 'Flex',
          policySummary: 'Flex fare allows changes before departure. Same-ticket connection remains protected if rebooked inside Aegean/OA inventory.',
        },
        {
          id: 'seg-santorini-hotel',
          kind: 'hotel',
          providerName: 'Caldera View Suites',
          title: '3 nights in Oia',
          startsAt: iso(48, 16),
          endsAt: iso(51, 11),
          confirmationCode: 'CVS-2044',
          routeSummary: null,
          fareClass: null,
          policySummary: 'Deposit is refundable until 7 days before arrival. After that, one-night deposit is retained.',
        },
      ],
      opportunities: [
        {
          id: 'opp-santorini-ferry-backup',
          tripId: 'mock-trip-santorini',
          kind: 'connection_risk',
          status: 'monitoring',
          title: 'Ferry backup held for wind risk',
          detail: 'High winds can disrupt island flights. Assist found a refundable ferry backup that preserves your Athens connection if JTR flights are delayed.',
          actionLabel: 'Hold backup',
          priority: 2,
          savingsAmount: null,
          protectedValue: 420,
          deadlineAt: iso(46, 18),
          autoActionable: false,
          citations: [
            {
              label: 'Island disruption rule',
              detail: 'Airline reaccommodation applies after cancellation, but ferry backup lowers missed-transatlantic risk before the waiver is triggered.',
            },
          ],
        },
        {
          id: 'opp-santorini-hotel-rate',
          tripId: 'mock-trip-santorini',
          kind: 'hotel_rate_drop',
          status: 'action_available',
          title: 'Suite rate dropped $214',
          detail: 'The same room type is available under the same refundable terms for less. Assist can rebook before the deposit deadline.',
          actionLabel: 'Rebook suite',
          priority: 1,
          savingsAmount: 214,
          protectedValue: null,
          deadlineAt: iso(41, 16),
          autoActionable: true,
          citations: [
            {
              label: 'Hotel rate rule',
              detail: 'Free cancellation applies until 7 days before arrival; replacement rate has the same room category and cancellation terms.',
            },
          ],
        },
      ],
      cancellation: {
        tripId: 'mock-trip-santorini',
        summary: 'Canceling today preserves airfare as credit and fully refunds the hotel deposit.',
        refundAmount: 1210,
        travelCreditAmount: 1380,
        feeAmount: 0,
        decisionWindowEndsAt: iso(41, 16),
        creditExpiresAt: iso(413, 0),
        risks: [
          'Airline credit may need to be reused on the same carrier family.',
          'Hotel deposit becomes nonrefundable after the 7-day cutoff.',
          'Replacement island flights are limited during wind events.',
        ],
      },
    },
    {
      tripId: 'mock-trip-lisbon-past',
      tripName: 'Lisbon 2026',
      tripTagline: 'The city in hills, music, and one last golden hour.',
      destinationName: 'Lisbon',
      destinationCountry: 'Portugal',
      status: 'completed',
      travelerCount: 3,
      totalCost: 4380,
      protectedValue: 84,
      potentialSavings: 0,
      monitoredAt,
      segments: [
        {
          id: 'seg-lisbon-flight',
          kind: 'flight',
          providerName: 'TAP Air Portugal',
          title: 'TP 204 · EWR to LIS',
          startsAt: iso(-7, 18),
          endsAt: iso(-6, 6),
          confirmationCode: 'TP3L9A',
          routeSummary: 'Newark to Lisbon, nonstop',
          fareClass: 'Economy Classic',
          policySummary: 'Trip completed. Residual seat-fee refund is being monitored through the operating carrier.',
        },
        {
          id: 'seg-lisbon-hotel',
          kind: 'hotel',
          providerName: 'Baixa House',
          title: '4 nights in Baixa',
          startsAt: iso(-6, 15),
          endsAt: iso(-2, 11),
          confirmationCode: 'BH-7621',
          routeSummary: null,
          fareClass: null,
          policySummary: 'Stay completed. Deposit was fully applied to the final folio.',
        },
      ],
      opportunities: [
        {
          id: 'opp-lisbon-refund',
          tripId: 'mock-trip-lisbon-past',
          kind: 'credit_protection',
          status: 'monitoring',
          title: '$84 seat-fee refund pending',
          detail: 'Assist is watching a post-trip ancillary refund from the return flight seat change.',
          actionLabel: 'Track refund',
          priority: 4,
          savingsAmount: null,
          protectedValue: 84,
          deadlineAt: iso(21, 12),
          autoActionable: false,
          citations: [
            {
              label: 'Carrier refund note',
              detail: 'Seat-fee refunds are reviewed after schedule changes when the assigned cabin seat is not delivered.',
            },
          ],
        },
      ],
      cancellation: {
        tripId: 'mock-trip-lisbon-past',
        summary: 'Trip completed. Assist is only monitoring post-trip refund and credit cleanup.',
        refundAmount: 84,
        travelCreditAmount: 0,
        feeAmount: 0,
        decisionWindowEndsAt: null,
        creditExpiresAt: null,
        risks: [
          'Refund timing depends on the airline processing queue.',
          'No cancellation action remains because travel is complete.',
        ],
      },
    },
  ];
}

export function getMockTripGuide(tripId: string): ActiveTripGuide | undefined {
  return listMockTripGuides().find((guide) => guide.tripId === tripId);
}
